var nome=prompt('Inserisci il tuo Nome');
console.log(nome);
var cognome=prompt('Inserisci il tuo Cognome');
console.log(cognome);
var colore=prompt('Inserisci il tuo colore preferito');
console.log(colore);
var password = nome+cognome+colore+'19';
document.getElementById('nome').innerHTML='Ciao '+nome;
document.getElementById('cognome').innerHTML=' '+cognome;
document.getElementById('colore').innerHTML='Il tuo colore preferito è '+colore;
document.getElementById('messaggio').innerHTML='La password generata per te è ';
document.getElementById('password').innerHTML=password;